{
  gStyle->SetOptFit(1111);
  double t_tot = 4109.0*3600.0;
  double n = 5;
  IBD *ibd = new IBD();
  TChain *ch = ibd->chain;
  double t_end = 100;
  new TCanvas;
  ch->Draw("ncapt_dt/1000>>hfar(12000,1000,13000)","cut&1<<0","goff");
  TH1D *hfar = (TH1D*)gDirectory->Get("hfar");
  hfar->Sumw2();
  hfar->Scale(1/hfar->GetBinWidth(1)/t_tot);
  hfar->SetLineColor(kMagenta);
  hfar->SetMarkerColor(kMagenta);
  hfar->SetTitle("Delayed Alpha Time - Prompt Alpha Time");
  gPad->Update();
  hfar->GetXaxis()->SetTitle("#Deltat (ms)");
  hfar->GetYaxis()->SetTitle("Rate (Hz/ms)");
  hfar->Draw();
  TF1 *fp0 = new TF1("fp0", "pol0", 2000, 12000);
  hfar->Fit(fp0,"r");
  new TCanvas;
  ch->Draw("ncapt_dt/1000>>h(130,0,130)","cut&1<<1","goff");
  TH1D *h = (TH1D*)gDirectory->Get("h");
  h->Sumw2();
  h->Scale(1/h->GetBinWidth(1)/t_tot);
  h->SetLineColor(kBlue);
  h->SetMarkerColor(kBlue);
  h->SetTitle("Delayed Alpha Time - Prompt Alpha Time");
  gPad->Update();
  h->GetXaxis()->SetTitle("#Deltat (#mus)");
  h->GetYaxis()->SetTitle("Rate (Hz/#mus)");
  h->Draw();
  TF1 *f = new TF1("f", "[0]*exp(-x/[1])+[2]", 1, 120);
  f->SetParameters(h->GetBinContent(2),50,fp0->GetParameter(0));
  f->SetParNames("R_{0}","#tau","Const");
  f->SetLineColor(kBlue);
  h->Fit(f,"r");
  new TCanvas;
  ch->Draw("(ncapt_dt-2e6)/80000>>hacc(130,0,130)","cut&1<<0&&ncapt_dt<11.6e6","goff");
  TH1D *hacc = (TH1D*)gDirectory->Get("hacc");
  hacc->Sumw2();
  hacc->Scale(1/hacc->GetBinWidth(1)/t_tot/80.0);
  hacc->SetLineColor(kMagenta);
  hacc->SetMarkerColor(kMagenta);
  hacc->SetTitle("Delayed Alpha Time - Prompt Alpha Time");
  gPad->Update();
  hacc->GetXaxis()->SetTitle("#Deltat (ms)");
  hacc->GetYaxis()->SetTitle("Rate (Hz/ms)");
  h->Draw();
  hacc->Draw("sames");
  TH1D *hsub = (TH1D*)h->Clone("hsub");
  hsub->Add(hacc,-1);
  hsub->SetLineColor(kRed);
  hsub->Draw("sames");
  f->SetLineColor(kRed);
  f->SetParameters(h->GetBinContent(2),50,0);
  hsub->Fit(f, "r");
  gPad->Update();
  hsub->SetTitle("Accidental Subtracted Delayed Alpha Time - Prompt Alpha Time");
  hsub->GetXaxis()->SetTitle("#Deltat (ms)");
  hsub->GetYaxis()->SetTitle("Rate (Hz/ms)");
}
